#!/bin/bash

# [1] Numeric Comparison

number=200

if [ $number -gt 200 ]; then
  echo "[1] Greater than 200."
else
  echo "[1] Smaller than 200."
fi

# [2]
# 2.1 Check the presence of files on the file system
# ~ is a home directory

if [ -f ~/node_modules ]; then
  echo "[2] The file exists."
else
  echo "[2] The file does not exist."
fi

# 2.2. Creating a bash script to install a package if it's not already installed

package=htop

if command -v $package; then
  echo "$package is available, let's run it..."
else
  echo "$package is NOT available, installing it..."
  # -y - don't give me a confirmation prompt, just go ahead and do it.
  sudo apt update && sudo apt install -y $package
fi

$package
