#!/bin/bash

# Math

var=1

while [ "$var" -le 10 ]; do
  echo "$var"
  var=$(($var + 1))
  sleep 0.5
done

# Another example on the Linux shell

while [ -f ~/testfile ]; do
  echo "As of $(date), the test file exists."
  sleep 5
done

echo "As of $(date), the test file has gone missing."
