#!/bin/bash

# NOTE: MacOS doesn't have `apt-get`

release_file=/etc/os-release
log_file=/var/log/updater.log
error_log_file=/var/log/updater_errors.log

check_exit_status() {
  if [ $? -ne 0 ]; then
    echo "An error occurred, please check the $error_log_file file."
    exit 1
  fi
}

if grep -q "Arch" $release_file; then
  # The host is based on Arch, run the pacman update command
  sudo pacman -Syu 1>>$log_file 2>>$error_log_file
  check_exit_status

fi

if grep -q "Pop" $release_file || grep -q "Ubuntu" $release_file; then
  sudo apt update 1>>$log_file 2>>$error_log_file
  check_exit_status

  sudo apt dist-upgrade 1>>$log_file 2>>$error_log_file
  check_exit_status
fi
