#!/bin/bash

ret=$?

# More efficiently utilizing Exit Codes

package=notexist

sudo apt install $package >>package_install_results.log

if [ $ret -eq 0 ]; then
  echo "The installation of $package was succesful."
  echo "The new command is available here:"
  which $package
else
  echo "$package failed to install." >>package_install_failure.log
fi

# An example script that illustrates why execution order is important

directory=/etc
if [ -d $directory ]; then
  echo "The directory $directory exists."
  exit 0
else
  echo "The directory $directory doesn't exist"
  exit 199
fi

echo "You didn't see this statement."
